- name: setup frontend component
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: Copy config file
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
    - name: setup nodejs repo
      ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: remove app content folder
      ansible.builtin.file:
        path: /tmp/frontend
        state: absent
    - name: create app content folder
      ansible.builtin.file:
        path: /tmp/frontend
        state: directory
    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/frontend.zip
        dest: /tmp/frontend
        remote_src: yes
    - name: build static code
      ansible.builtin.shell: npm install ; npm run build ; rm -rf /usr/share/nginx/html/* ; cp -r out/* /usr/share/nginx/html/
      args:
        chdir: /tmp/frontend
    - name: start nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: yes



